#!/usr/bin/python3

# Author: Angelus

import socket
import sys
import os
import time

pikachu = '''
	`;-.          ___,
  	`.`\_...._/`.-"`
    	\        /      ,
    	/()   () \    .' `-._
   	|)  .    ()\  /   _.'
   	\  -'-     ,; '. <   SMTP User ButeForce
    	;.__     ,;|   > 
   	/ ,    / ,  |.-'.-'
  	(_/    (_/ ,;|.<`
    	\    ,     ;-`
     	>   \    /
    	(_,-'`> .'
Pikachu   (_,'

'''

print(pikachu)
time.sleep(1)
print("\n [+] Pikachu-SMTP starting!\n")

if len(sys.argv) != 3:
    print("\n Usage: ./pikachu <target-ip> <wordlist> \n")
    sys.exit(0)

target_ip = sys.argv[1]
user_file = sys.argv[2]

if not os.path.exists(user_file):
    print('\n[!] File Not Found....exiting now..\n')
    sys.exit(0)

def brute(ip, word):
    s = socket.socket()
    s.connect((ip, 25))
    s.recv(1024)
    s.send(f'VRFY {user}\r\n'.encode())
    answer = s.recv(1024).decode()
    if "unknown" not in answer.lower():
        print(f"[+] {user} does exist")
    s.close()

with open(user_file, 'r') as file:
    for line in file.readlines():
        user = line.strip()
        brute(target_ip, user)
