#!/usr/bin/python3

#Author :: emrekybs


RED = '\033[1;31;48m'
WHITE = "\33[0m"
GREEN = '\033[1;32;48m'




import socket
import sys
import os
import time
import signal
import time
import threading



golo = '''
	`;-.          ___,
  	`.`\_...._/`.-"`
    	\        /      ,
    	/()   () \    .' `-._
   	|)  .    ()\  /   _.'
   	\  -'-     ,; '. <   SMTP User ButeForce
    	;.__     ,;|   > 
   	/ ,    / ,  |.-'.-'
  	(_/    (_/ ,;|.<`
    	\    ,     ;-`
     	>   \    /
    	(_,-'`> .'
Pikachu   (_,'

      '''

print(golo)
time.sleep(1)
print(f"\n [{GREEN}+{WHITE}] {RED}Pikachu-SMTP{WHITE} starting!\n")

if len(sys.argv) != 3:
	print(f"\n Usage: ./pikachu <{RED}target-ip{WHITE}> <{GREEN}wordlist{WHITE}> \n")
	sys.exit(0)

target_ip = sys.argv[1]
user_file = sys.argv[2]

if os.path.exists(user_file) == False:
	print(f'\n[{RED}!{WHITE}]File Not Found....exiting now..\n')
	sys.exit(0)

def brute(ip, word):
			
			s = socket.socket()
			s.connect((ip, 25))
			s.recv(1024)
			s.send(f'VRFY {user}\r\n'.encode())
			answer = s.recv(1024).decode()
			if not "unknown" in answer.lower():
				print(f"[{GREEN}+{WHITE}] {RED}{user}{WHITE} does exist")
			s.close()

with open(user_file, 'r') as file:
	for line in file.readlines():
		user = line.strip()
		brute(target_ip, user)
